// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmcmhioexiqrfdhjyxfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtY21oaW9leGlxcmZkaGp5eGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTcxNzQsImV4cCI6MjA3MTYzMzE3NH0.ME1pkaoKL_Eyc2btUj_by4Ah35DyMDAjdg4XHLyRHLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});